name: alotazrighat_application
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.0.15
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  uuid: ^3.0.7
  persian_datetime_picker: ^2.5.0
  animate_do: ^3.1.2
  awesome_dialog: ^3.0.2
  flutter_custom_clippers: ^2.1.0
  shamsi_date: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_spinkit: ^5.2.0
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.7
  connectivity_plus: ^4.0.2
  liquid_swipe: ^3.1.0
  dio: ^5.3.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  geolocator: ^10.0.1
  cupertino_icons: ^1.0.2
  form_validator: ^2.1.1
  flutter_map: ^5.0.0
  url_launcher: ^6.1.14
  flutter_rating_bar: ^4.0.1
  uni_links: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true

  assets:
   - assets/icons/
  

  fonts:
    - family: Iran Sans
      fonts:
        - asset: assets/fonts/IRANSansXFaNum-Bold.ttf
        - asset: assets/fonts/IRANSansXFaNum-Regular.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
